### ISSUE TITLE
yarn install throwing errors: error Command failed with exit code 1.

### ISSUE THREAD

**Issue by ashokganika** [tabler/tabler-react#473]
C:\Users\user\Desktop\my-apps>yarn start
yarn run v1.18.0-20190703.1445
$ react-scripts start
Starting the development server...

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jonthomp** [comment]
@ashokganika I don't see anything there related to tabler-react, please can you provide more details and maybe some code examples?
