### ISSUE TITLE
Heap out of memory issues when running `npm start` on branch version-2

### ISSUE THREAD

**Issue by yingw787** [tabler/tabler-react#522]
Hello,

I was interested in using tabler and specifically the preview-dev version, and I had wanted to see whether the Tabler React team was sync'ing with that branch. I cloned the repository, installed the dependencies, and then proceeded to get an out of memory error when compiling the TypeScript. I'm not quite sure what happened.

Here are various debug logs I've gotten from trying to run `npm start`:

```bash
Starting the development server...

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.5.0

YOUR TYPESCRIPT VERSION: 3.5.1

Please only submit bug reports when using the officially supported version.

=============
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
```

```json

{
  "header": {
    "reportVersion": 1,
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20200707.192439.1864345.0.001.json",
    "dumpEventTime": "2020-07-07T19:24:39Z",
    "dumpEventTimeStamp": "1594164279425",
    "processId": 1864345,
    "cwd": "/home/yingw787/src/tabler-react/example",
    "commandLine": [
      "node",
      "/home/yingw787/src/tabler-react/example/node_modules/react-app-rewired/scripts/start.js"
    ],
    "nodejsVersion": "v12.14.0",
    "glibcVersionRuntime": "2.31",
    "glibcVersionCompiler": "2.17",
    "wordSize": 64,
    "arch": "x64",
    "platform": "linux",
    "componentVersions": {
      "node": "12.14.0",
      "v8": "7.7.299.13-node.16",
      "uv": "1.33.1",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.39.2",
      "napi": "5",
      "llhttp": "1.1.4",
      "http_parser": "2.8.0",
      "openssl": "1.1.1d",
      "cldr": "35.1",
      "icu": "64.2",
      "tz": "2019c",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "lts": "Erbium",
      "headersUrl": "https://nodejs.org/download/release/v12.14.0/node-v12.14.0-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v12.14.0/node-v12.14.0.tar.gz"
    },
    "osName": "Linux",
    "osRelease": "5.4.0-37-generic",
    "osVersion": "#41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020",
    "osMachine": "x86_64",
    "cpus": [
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2746,
        "user": 1158791600,
        "nice": 1341000,
        "sys": 617990800,
        "idle": 14616714300,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2759,
        "user": 1158896100,
        "nice": 1270900,
        "sys": 618754300,
        "idle": 3245780100,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2758,
        "user": 1163990500,
        "nice": 1399300,
        "sys": 619576200,
        "idle": 3239905600,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2681,
        "user": 1154383700,
        "nice": 1320700,
        "sys": 632582200,
        "idle": 3243804800,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2757,
        "user": 1151702100,
        "nice": 1265600,
        "sys": 670828200,
        "idle": 3235684000,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2758,
        "user": 1196847300,
        "nice": 1320800,
        "sys": 642825700,
        "idle": 3210334800,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2748,
        "user": 1180429200,
        "nice": 1220600,
        "sys": 632038500,
        "idle": 3241494500,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2726,
        "user": 1159237700,
        "nice": 1262400,
        "sys": 623726000,
        "idle": 3246028200,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2724,
        "user": 1111381500,
        "nice": 1312200,
        "sys": 680604000,
        "idle": 3243246800,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2864,
        "user": 1136936300,
        "nice": 1214400,
        "sys": 634690300,
        "idle": 3242498400,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2734,
        "user": 1120049000,
        "nice": 1300100,
        "sys": 646669100,
        "idle": 3250294800,
        "irq": 0
      },
      {
        "model": "Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz",
        "speed": 2767,
        "user": 1117090000,
        "nice": 1340200,
        "sys": 655064600,
        "idle": 3237699100,
        "irq": 0
      }
    ],
    "networkInterfaces": [
      {
        "name": "lo",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "127.0.0.1",
        "netmask": "255.0.0.0",
        "family": "IPv4"
      },
      {
        "name": "wlp82s0",
        "internal": false,
        "mac": "94:e6:f7:1f:79:35",
        "address": "192.168.1.13",
        "netmask": "255.255.255.0",
        "family": "IPv4"
      },
      {
        "name": "tailscale0",
        "internal": false,
        "mac": "00:00:00:00:00:00",
        "address": "100.105.221.52",
        "netmask": "255.255.255.255",
        "family": "IPv4"
      },
      {
        "name": "lo",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "::1",
        "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "family": "IPv6",
        "scopeid": 0
      },
      {
        "name": "wlp82s0",
        "internal": false,
        "mac": "94:e6:f7:1f:79:35",
        "address": "fe80::1acd:14ff:2b2f:8224",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 3
      },
      {
        "name": "tailscale0",
        "internal": false,
        "mac": "00:00:00:00:00:00",
        "address": "fe80::23b1:5001:9bf4:877",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 4
      }
    ],
    "host": "yingw787-ThinkPad-P1-Gen-2"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x0000000000b04935",
      "symbol": "report::TriggerNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, std::string const&, v8::Local<v8::String>) [node]"
    },
    {
      "pc": "0x00000000009db9e3",
      "symbol": "node::OnFatalError(char const*, char const*) [node]"
    },
    {
      "pc": "0x0000000000b39f1e",
      "symbol": "v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]"
    },
    {
      "pc": "0x0000000000b3a299",
      "symbol": "v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]"
    },
    {
      "pc": "0x0000000000ce5635",
      "symbol": " [node]"
    },
    {
      "pc": "0x0000000000ce5cc6",
      "symbol": "v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]"
    },
    {
      "pc": "0x0000000000cf1b5a",
      "symbol": "v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]"
    },
    {
      "pc": "0x0000000000cf2a65",
      "symbol": "v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]"
    },
    {
      "pc": "0x0000000000cf5478",
      "symbol": "v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]"
    },
    {
      "pc": "0x0000000000cc30c6",
      "symbol": "v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [node]"
    },
    {
      "pc": "0x0000000000efbd12",
      "symbol": "v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [node]"
    },
    {
      "pc": "0x000000000103219c",
      "symbol": "v8::internal::Runtime_StringCharCodeAt(int, unsigned long*, v8::internal::Isolate*) [node]"
    },
    {
      "pc": "0x0000000001374fd9",
      "symbol": " [node]"
    }
  ],
  "javascriptHeap": {
    "totalMemory": 2159755264,
    "totalCommittedMemory": 2157856616,
    "usedMemory": 1766026832,
    "availableMemory": 151027488,
    "memoryLimit": 2197815296,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 262144,
        "committedMemory": 32568,
        "capacity": 261872,
        "used": 32296,
        "available": 229576
      },
      "new_space": {
        "memorySize": 33554432,
        "committedMemory": 33030608,
        "capacity": 16759808,
        "used": 1896064,
        "available": 14863744
      },
      "old_space": {
        "memorySize": 2022551552,
        "committedMemory": 2021617840,
        "capacity": 1745351344,
        "used": 1664237016,
        "available": 81114328
      },
      "code_space": {
        "memorySize": 2523136,
        "committedMemory": 2430592,
        "capacity": 2051936,
        "used": 2051936,
        "available": 0
      },
      "map_space": {
        "memorySize": 6295552,
        "committedMemory": 6176560,
        "capacity": 3430560,
        "used": 3430560,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 93945856,
        "committedMemory": 93945856,
        "capacity": 93828304,
        "used": 93828304,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 622592,
        "committedMemory": 622592,
        "capacity": 550656,
        "used": 550656,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 16759808,
        "used": 0,
        "available": 16759808
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 174.342,
    "kernelCpuSeconds": 22.5695,
    "cpuConsumptionPercent": 200.93,
    "maxRss": 2353532928,
    "pageFaults": {
      "IORequired": 0,
      "IONotRequired": 765015
    },
    "fsActivity": {
      "reads": 0,
      "writes": 32
    }
  },
  "uvthreadResourceUsage": {
    "userCpuSeconds": 85.4419,
    "kernelCpuSeconds": 7.99461,
    "cpuConsumptionPercent": 95.3434,
    "fsActivity": {
      "reads": 0,
      "writes": 24
    }
  },
  "libuv": [
  ],
  "environmentVariables": {
    "LESSOPEN": "| /usr/bin/lesspipe %s",
    "npm_config_cache_lock_stale": "60000",
    "npm_config_ham_it_up": "",
    "TMUX": "/tmp//tmux-1000/default,84578,0",
    "CONDA_PROMPT_MODIFIER": "(base) ",
    "npm_package_devDependencies__types_c3": "^0.7.0",
    "npm_config_legacy_bundling": "",
    "npm_config_sign_git_tag": "",
    "USER": "yingw787",
    "npm_package_dependencies__types_jest": "24.0.13",
    "npm_config_user_agent": "npm/6.14.4 node/v12.14.0 linux x64",
    "npm_config_always_auth": "",
    "npm_package_dependencies_formik": "^1.5.7",
    "npm_config_bin_links": "true",
    "npm_config_key": "",
    "SSH_AGENT_PID": "2408",
    "XDG_SESSION_TYPE": "x11",
    "npm_package_dependencies_d3_scale": "^3.0.0",
    "npm_config_allow_same_version": "",
    "npm_config_description": "true",
    "npm_config_fetch_retries": "2",
    "npm_config_heading": "npm",
    "npm_config_if_present": "",
    "npm_config_init_version": "1.0.0",
    "npm_config_user": "",
    "npm_node_execpath": "/usr/local/bin/node",
    "SHLVL": "2",
    "npm_config_prefer_online": "",
    "npm_config_noproxy": "",
    "QT4_IM_MODULE": "ibus",
    "HOME": "/home/yingw787",
    "CONDA_SHLVL": "1",
    "OLDPWD": "/home/yingw787/src/tabler-react",
    "npm_package_browserslist_production_0": ">0.2%",
    "npm_config_force": "",
    "DESKTOP_SESSION": "ubuntu",
    "npm_package_dependencies_react_syntax_highlighter": "^10.3.0",
    "npm_package_browserslist_production_1": "not dead",
    "npm_config_only": "",
    "npm_config_read_only": "",
    "npm_package_browserslist_production_2": "not op_mini all",
    "npm_config_cache_min": "10",
    "npm_config_init_license": "ISC",
    "GNOME_SHELL_SESSION_MODE": "ubuntu",
    "GTK_MODULES": "gail:atk-bridge",
    "npm_config_editor": "vi",
    "npm_config_rollback": "true",
    "npm_config_tag_version_prefix": "v",
    "MANAGERPID": "2174",
    "npm_config_cache_max": "Infinity",
    "npm_config_timing": "",
    "npm_config_userconfig": "/home/yingw787/.npmrc",
    "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
    "npm_package_dependencies_refractor": "^2.9.0",
    "npm_config_engine_strict": "",
    "npm_config_init_author_name": "",
    "npm_config_init_author_url": "",
    "npm_config_preid": "",
    "npm_config_tmp": "/tmp",
    "COLORTERM": "truecolor",
    "_CE_M": "",
    "npm_package_dependencies_c3": "^0.7.1",
    "npm_package_dependencies_react_router_dom": "^5.0.1",
    "npm_package_dependencies_react_scripts": "3.0.1",
    "npm_package_description": "This project was bootstrapped with [Create React App](https://github.com/facebookincubator/create-react-app).",
    "npm_config_depth": "Infinity",
    "npm_config_package_lock_only": "",
    "npm_config_save_dev": "",
    "npm_config_usage": "",
    "npm_package_dependencies__types_react": "16.8.19",
    "npm_package_devDependencies_react_apexcharts": "^1.3.3",
    "npm_package_readmeFilename": "README.md",
    "npm_config_metrics_registry": "https://registry.npmjs.org/",
    "npm_config_cafile": "",
    "npm_config_otp": "",
    "npm_config_package_lock": "true",
    "npm_config_progress": "true",
    "npm_config_https_proxy": "",
    "npm_config_save_prod": "",
    "MANDATORY_PATH": "/usr/share/gconf/ubuntu.mandatory.path",
    "IM_CONFIG_PHASE": "1",
    "npm_config_audit": "true",
    "npm_config_cidr": "",
    "npm_config_onload_script": "",
    "npm_config_sso_type": "oauth",
    "GTK_IM_MODULE": "ibus",
    "LOGNAME": "yingw787",
    "PYTHONDONTWRITEBYTECODE": "1",
    "npm_package_devDependencies_apexcharts": "^3.8.0",
    "npm_config_rebuild_bundle": "true",
    "npm_config_save_bundle": "",
    "npm_config_shell": "/bin/bash",
    "DESKTOP_AUTOSTART_ID": "10b0acef643fdcb68f159218796470925000000025020019",
    "JOURNAL_STREAM": "9:51911",
    "_": "/usr/local/bin/npm",
    "npm_package_private": "true",
    "npm_config_dry_run": "",
    "npm_config_format_package_lock": "true",
    "npm_config_prefix": "/usr/local",
    "XDG_SESSION_CLASS": "user",
    "DEFAULTS_PATH": "/usr/share/gconf/ubuntu.default.path",
    "npm_config_scope": "",
    "npm_config_browser": "",
    "npm_config_cache_lock_wait": "10000",
    "npm_config_ignore_prepublish": "",
    "npm_config_registry": "https://registry.npmjs.org/",
    "npm_config_save_optional": "",
    "npm_config_searchopts": "",
    "npm_config_versions": "",
    "USERNAME": "yingw787",
    "TERM": "screen-256color",
    "npm_config_cache": "/home/yingw787/.npm",
    "npm_config_proxy": "",
    "npm_config_send_metrics": "",
    "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated",
    "_CE_CONDA": "",
    "npm_package_scripts_start": "react-app-rewired start",
    "npm_config_global_style": "",
    "npm_config_ignore_scripts": "",
    "npm_config_version": "",
    "WINDOWPATH": "2",
    "npm_package_browserslist_development_0": "last 1 chrome version",
    "npm_config_local_address": "",
    "npm_config_viewer": "man",
    "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
    "PATH": "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/yingw787/src/tabler-react/example/node_modules/.bin:/home/yingw787/.pyenv/bin:/home/yingw787/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/home/yingw787/chomper/bin",
    "SESSION_MANAGER": "local/yingw787-ThinkPad-P1-Gen-2:@/tmp/.ICE-unix/2502,unix/yingw787-ThinkPad-P1-Gen-2:/tmp/.ICE-unix/2502",
    "INVOCATION_ID": "1cd2ea62b0de4fb38339b153e85d3154",
    "npm_package_name": "example-v2",
    "npm_package_browserslist_development_1": "last 1 firefox version",
    "npm_config_audit_level": "low",
    "npm_config_prefer_offline": "",
    "NODE": "/usr/local/bin/node",
    "XDG_MENU_PREFIX": "gnome-",
    "GNOME_TERMINAL_SCREEN": "/org/gnome/Terminal/screen/27017343_95d2_4cb7_bf2f_78c40cbc7c01",
    "XDG_RUNTIME_DIR": "/run/user/1000",
    "npm_package_browserslist_development_2": "last 1 safari version",
    "npm_config_color": "true",
    "npm_config_sign_git_commit": "",
    "DISPLAY": ":1",
    "npm_package_scripts_eject": "react-scripts eject",
    "npm_config_fetch_retry_mintimeout": "10000",
    "npm_config_maxsockets": "50",
    "npm_config_offline": "",
    "npm_config_sso_poll_frequency": "500",
    "LANG": "en_US.UTF-8",
    "XDG_CURRENT_DESKTOP": "ubuntu:GNOME",
    "npm_package_dependencies_react_dom": "^16.8.6",
    "npm_package_dependencies_react_simple_maps": "github:jonthomp/react-simple-maps#componentdidupdate",
    "npm_config_umask": "0002",
    "XMODIFIERS": "@im=ibus",
    "XDG_SESSION_DESKTOP": "ubuntu",
    "XAUTHORITY": "/run/user/1000/gdm/Xauthority",
    "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
    "GNOME_TERMINAL_SERVICE": ":1.89",
    "npm_package_dependencies__types_node": "12.0.5",
    "npm_config_fund": "true",
    "npm_config_fetch_retry_maxtimeout": "60000",
    "npm_config_loglevel": "notice",
    "npm_config_logs_max": "10",
    "npm_config_message": "%s",
    "npm_lifecycle_script": "react-app-rewired start",
    "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh",
    "CONDA_PYTHON_EXE": "/home/yingw787/anaconda3/bin/python",
    "npm_package_dependencies__types_react_router_dom": "^4.3.3",
    "npm_package_dependencies_tabler_react": "link:..",
    "npm_package_scripts_test": "react-app-rewired test",
    "npm_config_ca": "",
    "npm_config_cert": "",
    "npm_config_global": "",
    "npm_config_link": "",
    "SHELL": "/bin/bash",
    "npm_package_version": "0.1.0",
    "npm_config_access": "",
    "npm_config_also": "",
    "npm_config_save": "true",
    "npm_config_unicode": "true",
    "npm_lifecycle_event": "start",
    "QT_ACCESSIBILITY": "1",
    "GDMSESSION": "ubuntu",
    "npm_package_scripts_build": "react-app-rewired build",
    "npm_package_devDependencies_customize_cra": "^0.2.13",
    "npm_config_argv": "{\"remain\":[],\"cooked\":[\"start\"],\"original\":[\"start\"]}",
    "npm_config_before": "",
    "npm_config_long": "",
    "npm_config_production": "",
    "npm_config_searchlimit": "20",
    "npm_config_unsafe_perm": "true",
    "npm_config_update_notifier": "true",
    "LESSCLOSE": "/usr/bin/lesspipe %s %s",
    "CONDA_DEFAULT_ENV": "base",
    "npm_config_auth_type": "legacy",
    "npm_config_node_version": "12.14.0",
    "npm_config_tag": "latest",
    "npm_package_devDependencies_react_app_rewired": "^2.1.3",
    "npm_config_git_tag_version": "true",
    "npm_config_commit_hooks": "true",
    "npm_config_script_shell": "",
    "npm_config_shrinkwrap": "true",
    "GPG_AGENT_INFO": "/run/user/1000/gnupg/S.gpg-agent:0:1",
    "npm_package_dependencies_classnames": "^2.2.6",
    "npm_config_fetch_retry_factor": "10",
    "npm_config_save_exact": "",
    "npm_config_strict_ssl": "true",
    "QT_IM_MODULE": "ibus",
    "npm_config_dev": "",
    "npm_config_globalconfig": "/usr/local/etc/npmrc",
    "npm_config_init_module": "/home/yingw787/.npm-init.js",
    "npm_config_parseable": "",
    "PWD": "/home/yingw787/src/tabler-react/example",
    "npm_config_globalignorefile": "/usr/local/etc/npmignore",
    "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
    "XDG_CONFIG_DIRS": "/etc/xdg/xdg-ubuntu:/etc/xdg",
    "CONDA_EXE": "/home/yingw787/anaconda3/bin/conda",
    "CLUTTER_IM_MODULE": "ibus",
    "PYENV_ROOT": "/home/yingw787/.pyenv",
    "XDG_DATA_DIRS": "/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop",
    "npm_config_cache_lock_retries": "10",
    "npm_config_searchstaleness": "900",
    "npm_package_dependencies_prop_types": "^15.7.2",
    "npm_config_node_options": "",
    "npm_config_save_prefix": "^",
    "npm_config_scripts_prepend_node_path": "warn-only",
    "TMUX_PLUGIN_MANAGER_PATH": "/home/yingw787/.tmux/plugins/",
    "CONDA_PREFIX": "/home/yingw787/anaconda3",
    "npm_config_group": "1000",
    "npm_config_init_author_email": "",
    "npm_config_searchexclude": "",
    "VTE_VERSION": "6001",
    "TMUX_PANE": "%62",
    "npm_package_dependencies_typescript": "3.5.1",
    "npm_config_git": "git",
    "npm_config_optional": "true",
    "npm_package_dependencies__types_react_dom": "16.8.4",
    "npm_package_dependencies_react": "^16.8.6",
    "npm_package_eslintConfig_extends": "react-app",
    "npm_config_json": "",
    "INIT_CWD": "/home/yingw787/src/tabler-react/example",
    "NODE_ENV": "development",
    "NODE_PATH": "",
    "BABEL_ENV": "development"
  },
  "userLimits": {
    "core_file_size_blocks": {
      "soft": 0,
      "hard": "unlimited"
    },
    "data_seg_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "file_size_blocks": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_locked_memory_bytes": {
      "soft": 67108864,
      "hard": 67108864
    },
    "max_memory_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "open_files": {
      "soft": 1048576,
      "hard": 1048576
    },
    "stack_size_bytes": {
      "soft": 8388608,
      "hard": "unlimited"
    },
    "cpu_time_seconds": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_user_processes": {
      "soft": 255539,
      "hard": 255539
    },
    "virtual_memory_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    }
  },
  "sharedObjects": [
    "linux-vdso.so.1",
    "/lib/x86_64-linux-gnu/libdl.so.2",
    "/lib/x86_64-linux-gnu/libstdc++.so.6",
    "/lib/x86_64-linux-gnu/libm.so.6",
    "/lib/x86_64-linux-gnu/libgcc_s.so.1",
    "/lib/x86_64-linux-gnu/libpthread.so.0",
    "/lib/x86_64-linux-gnu/libc.so.6",
    "/lib64/ld-linux-x86-64.so.2",
    "/lib/x86_64-linux-gnu/libnss_files.so.2"
  ]
}
```

```bash
Compiling...

<--- Last few GCs --->

  [1864345:0x2efa070]    97865 ms: Scavenge 1701.8 (2065.0) -> 1686.5 (2065.0) MB, 9.3 / 0.0 ms  (average m
  u = 0.364, current mu = 0.370) allocation failure
[1864345:0x2efa070]    97892 ms: Scavenge 1702.2 (2065.0) -> 1687.4 (2066.0) MB, 9.2 / 0.0 ms  (average m
u = 0.364, current mu = 0.370) allocation failure
[1864345:0x2efa070]    97920 ms: Scavenge 1702.9 (2066.0) -> 1688.2 (2066.7) MB, 9.7 / 0.0 ms  (average m
u = 0.364, current mu = 0.370) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

   0: ExitFrame [pc: 0x1374fd9]
Security context: 0x0c0699b008a1 <JSObject>
   1: join [0x191d90a6e119] [path.js:~1034] [pc=0x3af5cbe6a617](this=0x24c9b0cc2581 <Object map = 0xc6f6
d5b0e01>)
   2: arguments adaptor frame: 2->0
   3: /* anonymous */ [0x35eaad6dd179] [/home/yingw787/src/tabler-react/example/node_modules/chokidar/li
b/nodefs-handler.js:396] [bytecode=0x53b12f7961 offset=181](this=0x0fa6a2687391 <FSWatcher map = 0x14eac1
51c...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200707.192439.1864345.0.001.json
Node.js report completed
1: 0x9da7c0 node::Abort() [node]
2: 0x9db976 node::OnFatalError(char const*, char const*) [node]
3: 0xb39f1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
4: 0xb3a299 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
5: 0xce5635  [node]
6: 0xce5cc6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
7: 0xcf1b5a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackF
lags) [node]
8: 0xcf2a65 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageColle
ctionReason, v8::GCCallbackFlags) [node]
9: 0xcf5478 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::intern
al::AllocationAlignment) [node]
10: 0xcc30c6 v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [node]
11: 0xefbd12 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal:
:ConsString>, v8::internal::AllocationType) [node]
12: 0x103219c v8::internal::Runtime_StringCharCodeAt(int, unsigned long*, v8::internal::Isolate*) [node]
13: 0x1374fd9  [node]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example-v2@0.1.0 start: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example-v2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yingw787/.npm/_logs/2020-07-07T23_24_39_652Z-debug.log
```

That log file:

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v12.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle example-v2@0.1.0~prestart: example-v2@0.1.0
6 info lifecycle example-v2@0.1.0~start: example-v2@0.1.0
7 verbose lifecycle example-v2@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle example-v2@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/yingw787/src/tabler-react/example/node_modules/.bin:/home/yingw787/.pyenv/bin:/home/yingw787/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/home/yingw787/chomper/bin
9 verbose lifecycle example-v2@0.1.0~start: CWD: /home/yingw787/src/tabler-react/example
10 silly lifecycle example-v2@0.1.0~start: Args: [ '-c', 'react-app-rewired start' ]
11 silly lifecycle example-v2@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle example-v2@0.1.0~start: Failed to exec start script
13 verbose stack Error: example-v2@0.1.0 start: `react-app-rewired start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid example-v2@0.1.0
15 verbose cwd /home/yingw787/src/tabler-react/example
16 verbose Linux 5.4.0-37-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error example-v2@0.1.0 start: `react-app-rewired start`
22 error Exit status 1
23 error Failed at the example-v2@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Are there recommendations for setting additional parameters or having a base level of dependencies?

I'm using yarn `1.22.0` and npm `6.14.4`. I have 64GB of RAM installed, so I don't think it's an issue with physical memory size but rather with a memory leak somewhere.

Would love to use `version-2` or at least check it out.

**Comment by yingw787** [comment]
Never mind, following the instructions in the README.md solved this issue. I'm going to go ahead and close out this issue.
